/*
* generated by Xtext
*/
package com.euclideanspace.macro.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DemoAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/euclideanspace/macro/parser/antlr/internal/InternalDemo.tokens");
	}
}
