/*
 * generated by Xtext
 */
package com.euclideanspace.xgener;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GenRuntimeModule extends com.euclideanspace.xgener.AbstractGenRuntimeModule {

}
