/*
* generated by Xtext
*/
package com.euclideanspace.xgener;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GenStandaloneSetup extends GenStandaloneSetupGenerated{

	public static void doSetup() {
		new GenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

