/*
* generated by Xtext
*/
package com.euclideanspace.xgener.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.euclideanspace.xgener.services.GenGrammarAccess;

public class GenParser extends AbstractContentAssistParser {
	
	@Inject
	private GenGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.euclideanspace.xgener.ui.contentassist.antlr.internal.InternalGenParser createParser() {
		com.euclideanspace.xgener.ui.contentassist.antlr.internal.InternalGenParser result = new com.euclideanspace.xgener.ui.contentassist.antlr.internal.InternalGenParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
					put(grammarAccess.getClassTypeAccess().getAlternatives_2(), "rule__ClassType__Alternatives_2");
					put(grammarAccess.getClassTypeAccess().getBlockingAlternatives_2_3_1_0(), "rule__ClassType__BlockingAlternatives_2_3_1_0");
					put(grammarAccess.getProcedureAccess().getAlternatives_2(), "rule__Procedure__Alternatives_2");
					put(grammarAccess.getProcedureAccess().getTypesAlternatives_2_2_1_0(), "rule__Procedure__TypesAlternatives_2_2_1_0");
					put(grammarAccess.getStatementAccess().getAlternatives_2(), "rule__Statement__Alternatives_2");
					put(grammarAccess.getExpressionAccess().getAlternatives_2(), "rule__Expression__Alternatives_2");
					put(grammarAccess.getExpressionAccess().getLiteralAlternatives_2_4_1_0(), "rule__Expression__LiteralAlternatives_2_4_1_0");
					put(grammarAccess.getMultIDAccess().getAlternatives(), "rule__MultID__Alternatives");
					put(grammarAccess.getMultStringAccess().getAlternatives(), "rule__MultString__Alternatives");
					put(grammarAccess.getClassTypeAccess().getGroup(), "rule__ClassType__Group__0");
					put(grammarAccess.getClassTypeAccess().getGroup_2_1(), "rule__ClassType__Group_2_1__0");
					put(grammarAccess.getClassTypeAccess().getGroup_2_2(), "rule__ClassType__Group_2_2__0");
					put(grammarAccess.getClassTypeAccess().getGroup_2_3(), "rule__ClassType__Group_2_3__0");
					put(grammarAccess.getProcedureAccess().getGroup(), "rule__Procedure__Group__0");
					put(grammarAccess.getProcedureAccess().getGroup_2_0(), "rule__Procedure__Group_2_0__0");
					put(grammarAccess.getProcedureAccess().getGroup_2_1(), "rule__Procedure__Group_2_1__0");
					put(grammarAccess.getProcedureAccess().getGroup_2_2(), "rule__Procedure__Group_2_2__0");
					put(grammarAccess.getStatementAccess().getGroup(), "rule__Statement__Group__0");
					put(grammarAccess.getStatementAccess().getGroup_2_0(), "rule__Statement__Group_2_0__0");
					put(grammarAccess.getStatementAccess().getGroup_2_1(), "rule__Statement__Group_2_1__0");
					put(grammarAccess.getStatementAccess().getGroup_2_2(), "rule__Statement__Group_2_2__0");
					put(grammarAccess.getStatementAccess().getGroup_2_3(), "rule__Statement__Group_2_3__0");
					put(grammarAccess.getStatementAccess().getGroup_2_3_2(), "rule__Statement__Group_2_3_2__0");
					put(grammarAccess.getStatementAccess().getGroup_2_4(), "rule__Statement__Group_2_4__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_0(), "rule__Expression__Group_2_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_1(), "rule__Expression__Group_2_1__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_2(), "rule__Expression__Group_2_2__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_3(), "rule__Expression__Group_2_3__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_4(), "rule__Expression__Group_2_4__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_5(), "rule__Expression__Group_2_5__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_6(), "rule__Expression__Group_2_6__0");
					put(grammarAccess.getExpressionAccess().getGroup_2_7(), "rule__Expression__Group_2_7__0");
					put(grammarAccess.getMultIDAccess().getGroup_1(), "rule__MultID__Group_1__0");
					put(grammarAccess.getMultStringAccess().getGroup_1(), "rule__MultString__Group_1__0");
					put(grammarAccess.getModelAccess().getClasAssignment_0(), "rule__Model__ClasAssignment_0");
					put(grammarAccess.getModelAccess().getProcAssignment_1(), "rule__Model__ProcAssignment_1");
					put(grammarAccess.getModelAccess().getStatemAssignment_2(), "rule__Model__StatemAssignment_2");
					put(grammarAccess.getModelAccess().getExpAssignment_3(), "rule__Model__ExpAssignment_3");
					put(grammarAccess.getClassTypeAccess().getNameAssignment_1(), "rule__ClassType__NameAssignment_1");
					put(grammarAccess.getClassTypeAccess().getNoclassAssignment_2_0(), "rule__ClassType__NoclassAssignment_2_0");
					put(grammarAccess.getClassTypeAccess().getPrefixAssignment_2_1_1(), "rule__ClassType__PrefixAssignment_2_1_1");
					put(grammarAccess.getClassTypeAccess().getSuffixAssignment_2_2_1(), "rule__ClassType__SuffixAssignment_2_2_1");
					put(grammarAccess.getClassTypeAccess().getBlockingAssignment_2_3_1(), "rule__ClassType__BlockingAssignment_2_3_1");
					put(grammarAccess.getProcedureAccess().getNameAssignment_1(), "rule__Procedure__NameAssignment_1");
					put(grammarAccess.getProcedureAccess().getPrefixAssignment_2_0_1(), "rule__Procedure__PrefixAssignment_2_0_1");
					put(grammarAccess.getProcedureAccess().getSuffixAssignment_2_1_1(), "rule__Procedure__SuffixAssignment_2_1_1");
					put(grammarAccess.getProcedureAccess().getTypesAssignment_2_2_1(), "rule__Procedure__TypesAssignment_2_2_1");
					put(grammarAccess.getStatementAccess().getNameAssignment_1(), "rule__Statement__NameAssignment_1");
					put(grammarAccess.getStatementAccess().getRepAssignment_2_0_1(), "rule__Statement__RepAssignment_2_0_1");
					put(grammarAccess.getStatementAccess().getUntilAssignment_2_0_3(), "rule__Statement__UntilAssignment_2_0_3");
					put(grammarAccess.getStatementAccess().getWhileAssignment_2_1_1(), "rule__Statement__WhileAssignment_2_1_1");
					put(grammarAccess.getStatementAccess().getDoAssignment_2_1_3(), "rule__Statement__DoAssignment_2_1_3");
					put(grammarAccess.getStatementAccess().getForAssignment_2_2_1(), "rule__Statement__ForAssignment_2_2_1");
					put(grammarAccess.getStatementAccess().getVarAssignment_2_3_1(), "rule__Statement__VarAssignment_2_3_1");
					put(grammarAccess.getStatementAccess().getExAssignment_2_3_2_1(), "rule__Statement__ExAssignment_2_3_2_1");
					put(grammarAccess.getStatementAccess().getValAssignment_2_4_1(), "rule__Statement__ValAssignment_2_4_1");
					put(grammarAccess.getStatementAccess().getExAssignment_2_4_3(), "rule__Statement__ExAssignment_2_4_3");
					put(grammarAccess.getExpressionAccess().getNameAssignment_1(), "rule__Expression__NameAssignment_1");
					put(grammarAccess.getExpressionAccess().getPrefixAssignment_2_0_1(), "rule__Expression__PrefixAssignment_2_0_1");
					put(grammarAccess.getExpressionAccess().getPar1Assignment_2_0_2(), "rule__Expression__Par1Assignment_2_0_2");
					put(grammarAccess.getExpressionAccess().getPar1Assignment_2_1_1(), "rule__Expression__Par1Assignment_2_1_1");
					put(grammarAccess.getExpressionAccess().getSuffixAssignment_2_1_2(), "rule__Expression__SuffixAssignment_2_1_2");
					put(grammarAccess.getExpressionAccess().getPar1Assignment_2_2_1(), "rule__Expression__Par1Assignment_2_2_1");
					put(grammarAccess.getExpressionAccess().getInfixAssignment_2_2_2(), "rule__Expression__InfixAssignment_2_2_2");
					put(grammarAccess.getExpressionAccess().getPar2Assignment_2_2_3(), "rule__Expression__Par2Assignment_2_2_3");
					put(grammarAccess.getExpressionAccess().getPar1Assignment_2_3_1(), "rule__Expression__Par1Assignment_2_3_1");
					put(grammarAccess.getExpressionAccess().getInfixleftAssignment_2_3_2(), "rule__Expression__InfixleftAssignment_2_3_2");
					put(grammarAccess.getExpressionAccess().getPar2Assignment_2_3_3(), "rule__Expression__Par2Assignment_2_3_3");
					put(grammarAccess.getExpressionAccess().getLiteralAssignment_2_4_1(), "rule__Expression__LiteralAssignment_2_4_1");
					put(grammarAccess.getExpressionAccess().getBracketAssignment_2_5_1(), "rule__Expression__BracketAssignment_2_5_1");
					put(grammarAccess.getExpressionAccess().getBracesAssignment_2_6_1(), "rule__Expression__BracesAssignment_2_6_1");
					put(grammarAccess.getExpressionAccess().getParenthasisAssignment_2_7_1(), "rule__Expression__ParenthasisAssignment_2_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.euclideanspace.xgener.ui.contentassist.antlr.internal.InternalGenParser typedParser = (com.euclideanspace.xgener.ui.contentassist.antlr.internal.InternalGenParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
