/*
* generated by Xtext
*/
package com.euclideanspace.pbase;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TutorialStandaloneSetup extends TutorialStandaloneSetupGenerated{

	public static void doSetup() {
		new TutorialStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

