/*
* generated by Xtext
*/
package com.euclideanspace.phantom1.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.euclideanspace.phantom1.services.Test1GrammarAccess;

public class Test1Parser extends AbstractContentAssistParser {
	
	@Inject
	private Test1GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.euclideanspace.phantom1.ui.contentassist.antlr.internal.InternalTest1Parser createParser() {
		com.euclideanspace.phantom1.ui.contentassist.antlr.internal.InternalTest1Parser result = new com.euclideanspace.phantom1.ui.contentassist.antlr.internal.InternalTest1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRecurseAccess().getAlternatives(), "rule__Recurse__Alternatives");
					put(grammarAccess.getRecurseAccess().getGroup_1(), "rule__Recurse__Group_1__0");
					put(grammarAccess.getModelAccess().getContentsAssignment(), "rule__Model__ContentsAssignment");
					put(grammarAccess.getRecurseAccess().getNAssignment_0(), "rule__Recurse__NAssignment_0");
					put(grammarAccess.getRecurseAccess().getRAssignment_1_1(), "rule__Recurse__RAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.euclideanspace.phantom1.ui.contentassist.antlr.internal.InternalTest1Parser typedParser = (com.euclideanspace.phantom1.ui.contentassist.antlr.internal.InternalTest1Parser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Test1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Test1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
