/*
 * generated by Xtext
 */
package com.euclideanspace.phantom1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Test1UiModule extends com.euclideanspace.phantom1.ui.AbstractTest1UiModule {
	public Test1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
