/*
 * generated by Xtext
 */
package com.euclideanspace.phantom1.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTest1Validator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.euclideanspace.phantom1.test1.Test1Package.eINSTANCE);
		return result;
	}
}
