/*
* generated by Xtext
*/
package com.euclideanspace.phantom1.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.euclideanspace.phantom1.services.Test1GrammarAccess;

public class Test1Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Test1GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.euclideanspace.phantom1.parser.antlr.internal.InternalTest1Parser createParser(XtextTokenStream stream) {
		return new com.euclideanspace.phantom1.parser.antlr.internal.InternalTest1Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public Test1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Test1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
