/*
* generated by Xtext
*/
package com.euclideanspace.phantom1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Test1AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/euclideanspace/phantom1/parser/antlr/internal/InternalTest1.tokens");
	}
}
