/*
* generated by Xtext
*/
package com.euclideanspace.whitespaceblock;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DemoStandaloneSetup extends DemoStandaloneSetupGenerated{

	public static void doSetup() {
		new DemoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

