/*
 * generated by Xtext
 */
package com.euclideanspace.whitespaceblock;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DemoRuntimeModule extends com.euclideanspace.whitespaceblock.AbstractDemoRuntimeModule {
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {
		return com.euclideanspace.whitespaceblock.DemoParser.class;
	}
}
