/*
 * generated by Xtext
 */
package com.euclideanspace.phantom1;

import org.eclipse.xtext.nodemodel.impl.NodeModelBuilder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Test1RuntimeModule extends com.euclideanspace.phantom1.AbstractTest1RuntimeModule {
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {
		return com.euclideanspace.phantom1.Test1Parser.class;
	}

  // contributed by org.eclipse.xtext.generator.serializer.SerializerFragment
//  public Class<? extends org.eclipse.xtext.serializer.sequencer.ISyntacticSequencer> bindISyntacticSequencer() {
//    return Test1OverrideSyntacticSequencer.class;
//  }

	/**
	 * Customise the node model builder to investigate how it works.
	 */
	public Class<? extends NodeModelBuilder> bindNodeModelBuilder() {
      return Test1NodeModelBuilder.class;
    }
}